### ISSUE TITLE
Add backups of the database

### ISSUE THREAD

**Issue by guhur** [MieuxVoter/majority-judgment-api-python#33]
We need a system to automatize the backup of the database. A simple error is so easy to break down everything.

It seems that this package allows to do it, simply:
https://github.com/kartoza/docker-pg-backup

**Comment by HermessNRJ** [comment]
To make the most approved system backup and have the most functionality is:
[django-dbbackup](https://github.com/django-dbbackup/django-dbbackup)

This allow us to : 
- make regular backups
- protect it with a GPG key
 - do version management

**Comment by guhur** [comment]
That sounds great
